pretrained_model_path: ./checkpoints/stable-diffusion-v1-4
output_dir: ./outputs/loveu-tgve-2023/DAVIS_480p/mbike-trick
train_data:
  video_path: ./data/loveu-tgve-2023/DAVIS_480p/480p_frames/mbike-trick
  prompt: A person on a motorcycle does a burnout on the road.
  height: 480
  width: 480
  num_frames: 32
  frame_rate: 1
validation_data:
  prompts:
    style: A person on a motorcycle does a burnout on the road, neon color style.
    object: A person on a bicycle does a wheelie on the road.
    background: A person on a motorcycle does a burnout on a frozen lake.
    multiple: A person on a scooter does a burnout on a frozen lake, sepia tone.
  height: 480
  width: 480
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 100
validation_steps: 100
trainable_modules:
- attn1.to_q
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
