pretrained_model_path: ./checkpoints/stable-diffusion-v1-4
output_dir: ./outputs/loveu-tgve-2023/youtube_480p/basketball-shot
train_data:
  video_path: ./data/loveu-tgve-2023/youtube_480p/480p_frames/basketball-shot
  prompt: Tap Nixon shooting a basketball while another man helps him.
  height: 480
  width: 480
  num_frames: 128
  frame_rate: 1
validation_data:
  prompts:
    style: Tap Nixon shooting a basketball while another man helps him, claymation
      style
    object: Tap Nixon shooting a rocket while another man helps him.
    background: Tap Nixon shooting a basketball on Mars.
    multiple: Tap Nixon shooting a basketball while a woman helps him, high-contrast
      style.
  height: 480
  width: 480
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 100
validation_steps: 100
trainable_modules:
- attn1.to_q
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
