pretrained_model_path: ./checkpoints/stable-diffusion-v1-4
output_dir: ./outputs/loveu-tgve-2023/youtube_480p/cat-dog-play
train_data:
  video_path: ./data/loveu-tgve-2023/youtube_480p/480p_frames/cat-dog-play
  prompt: A cat and a dog playing on the street while a girl walks around them.
  height: 480
  width: 480
  num_frames: 128
  frame_rate: 1
validation_data:
  prompts:
    style: A cat and a dog playing on the street while a girl walks around them, soft
      focus style.
    object: A beaver and a skunk playing in the street while a girl walks around them.
    background: A cat and a dog playing on the grass while a girl walks around them.
    multiple: A cat and a dog playing on the beach while a girl walks around them,
      golden hour lighting.
  height: 480
  width: 480
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 100
validation_steps: 100
trainable_modules:
- attn1.to_q
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
