pretrained_model_path: ./checkpoints/stable-diffusion-v1-4
output_dir: ./outputs/loveu-tgve-2023/youtube_480p/squirrel-climb
train_data:
  video_path: ./data/loveu-tgve-2023/youtube_480p/480p_frames/squirrel-climb
  prompt: 'The squirrel is climbing down a tree in a wooded park.  '
  height: 480
  width: 480
  num_frames: 128
  frame_rate: 1
validation_data:
  prompts:
    style: The squirrel is climbing down a tree in a wooded park, Van Gogh style.
    object: The cute yellow leopard is climbing down a tree in a wooded park.
    background: The squirrel is climbing down a tree in a forest of cherry blossoms.
    multiple: The squirrel is climbing up a tree in a wooded park, soft-focus style.
  height: 480
  width: 480
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 100
validation_steps: 100
trainable_modules:
- attn1.to_q
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
