pretrained_model_path: ./checkpoints/stable-diffusion-v1-4
output_dir: ./outputs/loveu-tgve-2023/youtube_480p/volleyball
train_data:
  video_path: ./data/loveu-tgve-2023/youtube_480p/480p_frames/volleyball
  prompt: A woman practices hitting a volleyball by a gym wall.
  height: 480
  width: 480
  num_frames: 128
  frame_rate: 1
validation_data:
  prompts:
    style: A woman practices hitting a volleyball by a gym wall, subdued color palette.
    object: A woman practices hitting a firecracker by a gym wall.
    background: A woman practices hitting a volleyball in a wooded setting.
    multiple: A woman practices hitting a firecracker in a natural setting.
  height: 480
  width: 480
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 100
validation_steps: 100
trainable_modules:
- attn1.to_q
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
