pretrained_model_path: ./checkpoints/stable-diffusion-v1-4
output_dir: ./outputs/loveu-tgve-2023/youtube_480p/weightlifting-sofa
train_data:
  video_path: ./data/loveu-tgve-2023/youtube_480p/480p_frames/weightlifting-sofa
  prompt: A woman lifts weights near a sofa.
  height: 480
  width: 480
  num_frames: 128
  frame_rate: 1
validation_data:
  prompts:
    style: A woman lifts weights near a sofa made of stained glass.
    object: A man lifts weights near a sofa.
    background: A woman lifts weights with the San Francisco skyline in the background.
    multiple: A woman lifts a car tire with the San Francisco skyline in the background.
  height: 480
  width: 480
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 100
validation_steps: 100
trainable_modules:
- attn1.to_q
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
