pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "./outputs/xxx"

train_data:
  video_path: "data/xxx.mp4"
  prompt: "xxx"
  height: 480
  width: 480

validation_data:
  prompts:
    - "xxx"
  height: 480
  width: 480
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 100
validation_steps: 100
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
