pretrained_model_path: ./checkpoints/stable-diffusion-v1-4
output_dir: ./outputs/loveu-tgve-2023/videvo_480p/earth-full-view
train_data:
  video_path: ./data/loveu-tgve-2023/videvo_480p/480p_frames/earth-full-view
  prompt: Full view of the Earth as it moves slowly toward the sun.
  height: 480
  width: 480
  num_frames: 32
  frame_rate: 1
validation_data:
  prompts:
    style: Full view of the Earth, made out of chocolate, as it moves slowly toward
      the sun.
    object: Full view of Mars as it moves slowly toward the sun.
    background: Full view of the Earth as it moves slowly through a fireworks display.
    multiple: Full view of the Mars as it moves slowly toward the sun, with fireworks
      in the background.
  height: 480
  width: 480
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 100
validation_steps: 100
trainable_modules:
- attn1.to_q
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
