pretrained_model_path: ./checkpoints/stable-diffusion-v1-4
output_dir: ./outputs/loveu-tgve-2023/videvo_480p/horizontal-match-striking
train_data:
  video_path: ./data/loveu-tgve-2023/videvo_480p/480p_frames/horizontal-match-striking
  prompt: An extreme close up video of someone striking a matchstick horizontally.
  height: 480
  width: 480
  num_frames: 32
  frame_rate: 1
validation_data:
  prompts:
    style: An extreme close up video of someone striking a matchstick horizontally,
      neon style.
    object: An extreme close up video of someone striking a lighter horizontally.
    background: An extreme close up video of someone striking a matchstick horizontally
      against a pool of water.
    multiple: An extreme close up video of someone striking a lighter horizontally,
      with sparks flying off.
  height: 480
  width: 480
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 100
validation_steps: 100
trainable_modules:
- attn1.to_q
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
