pretrained_model_path: ./checkpoints/stable-diffusion-v1-4
output_dir: ./outputs/loveu-tgve-2023/videvo_480p/setting-sun
train_data:
  video_path: ./data/loveu-tgve-2023/videvo_480p/480p_frames/setting-sun
  prompt: The sun setting with clouds moving around it.
  height: 480
  width: 480
  num_frames: 32
  frame_rate: 1
validation_data:
  prompts:
    style: The sun setting with clouds moving around it, 2D vector animation.
    object: A flying saucer moving with clouds moving around it.
    background: The sun setting with a clear sky.
    multiple: The moon setting with clouds moving around it, reflecting on a flooded
      road.
  height: 480
  width: 480
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 100
validation_steps: 100
trainable_modules:
- attn1.to_q
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
