pretrained_model_path: ./checkpoints/stable-diffusion-v1-4
output_dir: ./outputs/loveu-tgve-2023/videvo_480p/ship-sailing
train_data:
  video_path: ./data/loveu-tgve-2023/videvo_480p/480p_frames/ship-sailing
  prompt: 'A ship sails on the sea during sunset. '
  height: 480
  width: 480
  num_frames: 32
  frame_rate: 1
validation_data:
  prompts:
    style: A ship sails on the sea during sunset, 2D vector art.
    object: A toy sailboat sails on the sea during sunset.
    background: A ship sails on the the lunar surface during sunset.
    multiple: A toy sailboat sails on the sea during sunset with a dramatic sky full
      of colorful clouds.
  height: 480
  width: 480
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
learning_rate: 3.0e-05
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 100
validation_steps: 100
trainable_modules:
- attn1.to_q
- attn2.to_q
- attn_temp
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true
